customhost = "database-1.cxjyk20q7yhf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "powzhengteng-employee"
customregion = "us-east-1"
